'use strict';
// Pure screen-building functions for the Telegram bot. No network I/O, no
// mutable state — both live in server.js. Every export here is a plain
// data-in/data-out transform, unit-tested by tests/bot-ui-check.mjs.
//
// ctx = { contacts, from, isOwner }:
//  - contacts: the CONTACTS object server.js loads from assets/contacts.js
//    (may be null — every renderer here must still work).
//  - from: the Telegram `from` user object off the update (may be absent).
//  - isOwner: true when the chat is one of TG_LEAD_CHAT_IDS.
//
// Content (site-sourced facts) comes from bot-content.js (generated by
// gen-bot-content.mjs — regenerate it after any site text/price change).
// Bot-only microcopy (buttons, prompts, toasts) is typed out here, limited to
// the strings given in bot-ux SPEC.md sections 3-5 and FIXES.md section B —
// nothing improvised.
//
// Layout rules (FIXES.md section B): every content screen ends with a row that
// holds "← Меню"; two buttons share a row only when both labels are at most
// 17 characters (back-button pairs "← X" / "← Меню" are short by design);
// list lines start with "• "; prices never break inside "от 7 000 ₽".

const C = require('./bot-content.js');

// Lookups keyed by callback_data must only ever hit own keys: "constructor",
// "__proto__" or "toString" from a crafted button must not resolve to
// Object.prototype members.
function hasOwn(obj, key) { return Object.prototype.hasOwnProperty.call(obj, key); }

// ---------------------------------------------------------------------------
// small builders
// ---------------------------------------------------------------------------

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
const esc = escapeHtml;
function b(s) { return '<b>' + esc(s) + '</b>'; }
function i(s) { return '<i>' + esc(s) + '</i>'; }
function bullets(items) { return items.map((t) => '• ' + esc(t)).join('\n'); }
function numberedList(items) { return items.map((t, n) => (n + 1) + '. ' + esc(t)).join('\n'); }
// "от 7 000 ₽" -> the same with U+00A0 inside: Telegram must not wrap a price
// across lines. Only the "от … ₽" part is glued ("/ точка" after it is not).
function nbspPrice(price) {
  return String(price).replace(/(?:от\s)?\d[\d\s]*₽/g, (m) => m.replace(/\s/g, '\u00A0'));
}
function priceLine(label, price) { return esc(label) + ' — ' + b(nbspPrice(price)); }
function numberedBlock(s) { return b(s.n + ' · ' + s.title) + '\n' + esc(s.desc); }
function titleDescBlock(item) { return b(item.title) + '\n' + esc(item.desc); }
function bulletTitleDescLine(item) { return '• ' + b(item.title) + ' — ' + esc(item.desc); }
function qaBlock(item) { return b(item.q) + '\n' + esc(item.a); }

function btn(text, data) { return { text, callback_data: data }; }
function urlBtn(text, url) { return { text, url }; }
function kb(rows) { return { inline_keyboard: rows }; }
// Buttons "1".."N", three to a row: the questions themselves are listed in
// the screen text, too long for button labels.
function numberRows(count, dataFor) {
  const rows = [];
  for (let n = 0; n < count; n++) {
    if (n % 3 === 0) rows.push([]);
    rows[rows.length - 1].push(btn(String(n + 1), dataFor(n)));
  }
  return rows;
}

const DISABLE_PREVIEW = { is_disabled: true };

// The menu cover and the documents album are fetched by Telegram's own servers.
// The site's host (shared hosting) turns most of those fetches away — live test
// 02.10: "failed to get HTTP URL content" / WEBPAGE_CURL_FAILED for 4 of 5 photos
// — while the bot server's own host served every one. server.js passes its own
// origin as ctx.assetOrigin ("https://host/"); anything else (absent, not a bare
// https origin) means the site URL.
function assetBase(origin) {
  return typeof origin === 'string' && /^https:\/\/[A-Za-z0-9.-]+(:\d+)?\/?$/.test(origin)
    ? origin.replace(/\/?$/, '/')
    : C.siteUrl;
}
function coverPreview(origin) {
  return { url: assetBase(origin) + 'assets/bot-cover-v2.jpg', prefer_large_media: true, show_above_text: true };
}

// ---------------------------------------------------------------------------
// Lead services (section 4): short picker labels by LM_SERVICES index — the
// full label stored in the lead is the LM_SERVICES entry.
// ---------------------------------------------------------------------------

const LEAD_SERVICES = [
  'Межевание',
  'Технический план',
  'Раздел, объединение, перераспределение',
  'Акт обследования',
  'Акт осмотра объекта',
  'Вынос точек в натуру',
  'Другое / не знаю точно',
];
// Services without a page of their own (Акт обследования, Акт осмотра объекта,
// Вынос точек в натуру): title, note and price from the site, see
// gen-bot-content.mjs. Own keys only, like every callback lookup.
const EXTRA_SERVICES = Object.freeze(Object.assign(Object.create(null), ...C.extraServices.map((s) => ({ [s.id]: s }))));
const EXTRA_IDS = C.extraServices.map((s) => s.id);

// mezh/tehplan/razdel map onto the first three LM_SERVICES entries — same
// verbatim strings and order the site's own LeadModal already uses; the
// services without a page carry their LM_SERVICES index with them.
const SERVICE_ID_TO_LM_INDEX = Object.freeze(Object.assign(Object.create(null), { mezh: 0, tehplan: 1, razdel: 2 },
  ...C.extraServices.map((s) => ({ [s.id]: s.lmIndex }))));

// ---------------------------------------------------------------------------
// Callback grammar (section 3 + FIXES.md: h:d, l:e, l:e:s|n|p|c, l:b)
// ---------------------------------------------------------------------------

const SERVICE_IDS = C.serviceOrder; // ['mezh', 'tehplan', 'razdel']

// Exact callback strings. A Map, so inherited names can never match.
const FIXED_ROUTES = new Map([
  ['m', { type: 'menu' }],
  ['s', { type: 'services' }],
  ['services', { type: 'services' }], // legacy callback from the pre-redesign bot
  ['p', { type: 'prices' }],
  ['h', { type: 'how' }],
  ['h:d', { type: 'howDocs' }],
  ['a', { type: 'about' }],
  ['a:p', { type: 'projects' }],
  ['a:d', { type: 'documents' }],
  ['r', { type: 'reviews' }],
  ['f', { type: 'faqList' }],
  ['c', { type: 'contacts' }],
  ['contacts', { type: 'contacts' }], // legacy callback from the pre-redesign bot
  ['l', { type: 'leadStart' }],
  ['l:me', { type: 'leadUseName' }],
  ['l:skip', { type: 'leadSkip' }],
  ['l:ok', { type: 'leadConfirm' }],
  ['l:x', { type: 'leadCancel' }],
  ['l:e', { type: 'leadEditMenu' }],
  ['l:b', { type: 'leadBack' }],
  ['l:e:s', { type: 'leadEditField', field: 'service' }],
  ['l:e:n', { type: 'leadEditField', field: 'name' }],
  ['l:e:p', { type: 'leadEditField', field: 'phone' }],
  ['l:e:c', { type: 'leadEditField', field: 'comment' }],
]);

// "q12" / "l:o3": a position in a list, or -1 when out of range.
function indexIn(list, digits) {
  const n = Number(digits);
  return Number.isInteger(n) && n >= 0 && n < list.length ? n : -1;
}

function route(data) {
  const d = typeof data === 'string' ? data : '';
  const fixed = FIXED_ROUTES.get(d);
  if (fixed) return Object.assign({}, fixed);
  let m;
  if ((m = /^q(\d{1,3})$/.exec(d))) {
    const n = indexIn(C.faq, m[1]);
    return n < 0 ? null : { type: 'faqAnswer', n };
  }
  if ((m = /^s:([a-z]{1,20})(?::(w|f|q(\d{1,3})))?$/.exec(d))) {
    const id = m[1];
    // A service without a page has one screen: no steps, no FAQ.
    if (hasOwn(EXTRA_SERVICES, id)) return m[2] ? null : { type: 'extraService', id };
    if (!hasOwn(C.services, id)) return null;
    if (!m[2]) return { type: 'service', id };
    if (m[2] === 'w') return { type: 'serviceSteps', id };
    if (m[2] === 'f') return { type: 'serviceFaqList', id };
    const n = indexIn(C.services[id].faq, m[3]);
    return n < 0 ? null : { type: 'serviceFaqAnswer', id, n };
  }
  // Anything else under "l" is a request-form button that no longer exists
  // or never did (old "l:edit", an option out of range, an unknown service):
  // the flow answers it as stale and offers the menu.
  if (d === 'l' || d.indexOf('l:') === 0) {
    if ((m = /^l:o(\d{1,2})$/.exec(d))) {
      const n = indexIn(LEAD_SERVICES, m[1]);
      if (n >= 0) return { type: 'leadOption', n };
    }
    if ((m = /^l:([a-z]{1,20})$/.exec(d)) && hasOwn(SERVICE_ID_TO_LM_INDEX, m[1])) return { type: 'leadStartService', id: m[1] };
    return { type: 'leadUnknown' };
  }
  return null;
}

const FLOW_ROUTE_TYPES = new Set([
  'leadStart', 'leadStartService', 'leadOption', 'leadUseName', 'leadSkip', 'leadConfirm', 'leadCancel',
  'leadEditMenu', 'leadEditField', 'leadBack', 'leadUnknown',
]);
function isFlowRoute(r) { return !!r && FLOW_ROUTE_TYPES.has(r.type); }

// Typed commands -> routes (section 3's command table).
function commandRoute(command) {
  const cmd = String(command || '').toLowerCase();
  if (cmd === 'start' || cmd === 'menu' || cmd === 'help') return { type: 'menu' };
  if (cmd === 'services') return { type: 'services' };
  if (cmd === 'prices') return { type: 'prices' };
  if (cmd === 'faq') return { type: 'faqList' };
  if (cmd === 'contacts') return { type: 'contacts' };
  if (cmd === 'about') return { type: 'about' };
  if (cmd === 'reviews') return { type: 'reviews' };
  if (cmd === 'request') return { type: 'leadStart' };
  if (cmd === 'cancel') return { type: 'menu' }; // caller cancels the active flow as a side effect first
  return { type: 'menu' }; // unknown commands -> menu
}

// /start <payload> deep link. The owner-code check happens in server.js
// before this is ever consulted.
function startPayloadRoute(payload) {
  const p = String(payload || '').toLowerCase();
  if (p === 'request') return { type: 'leadStart' };
  if (SERVICE_IDS.includes(p)) return { type: 'service', id: p };
  if (EXTRA_IDS.includes(p)) return { type: 'extraService', id: p };
  if (p === 'prices') return { type: 'prices' };
  if (p === 'faq') return { type: 'faqList' };
  if (p === 'contacts') return { type: 'contacts' };
  if (p === 'about') return { type: 'about' };
  if (p === 'reviews') return { type: 'reviews' };
  return { type: 'menu' };
}

// ---------------------------------------------------------------------------
// Bot-only chrome shared across screens (strings given verbatim in SPEC.md
// section 3 and FIXES.md section B — not re-asserted against the site).
// ---------------------------------------------------------------------------

const LBL_REQUEST = 'Оставить заявку';
const LBL_MENU_BACK = '← Меню';
const LBL_SERVICES_BACK = '← Услуги';
const LBL_SERVICE_BACK = '← Услуга';
const LBL_FAQ_BACK = '← Вопросы';
const LBL_ABOUT_BACK = '← О компании';
const LBL_OPEN_SITE = 'Открыть сайт ↗';
const LBL_SITE_PAGE = 'Страница на сайте ↗';
const LBL_HOW = 'Как проходит работа';
const LBL_SERVICE_FAQ = 'Вопросы по услуге';
const LBL_SRO = 'Проверить аттестат ↗';
const LBL_POLICY = 'Политика конфиденциальности ↗';
const PRICE_HEADING = 'Стоимость';

// ---------------------------------------------------------------------------
// Screens (section 3). screen(route, ctx) handles navigation only — the lead
// flow (routes starting with "l") is driven by server.js's state machine
// using the leadFlow helpers further down.
// ---------------------------------------------------------------------------

function screenMenu(ctx) {
  const parts = C.home.eyebrow.split(' · ');
  const eyebrowTitle = parts[0];
  const eyebrowSub = parts.slice(1).join(' · ');
  const text = [
    b(eyebrowTitle),
    esc(eyebrowSub),
    '',
    b(C.home.title),
    esc(C.home.lead),
    '',
    i(C.home.tagline) + ' · ' + esc(C.home.consultFree),
  ].join('\n');
  const rows = [
    [btn(LBL_REQUEST, 'l')],
    [btn('Услуги', 's'), btn('Цены', 'p')],
    [btn(C.process.kicker, 'h'), btn(C.about.kicker, 'a')],
    [btn('Отзывы', 'r'), btn('Частые вопросы', 'f')],
    [btn('Контакты', 'c'), urlBtn(LBL_OPEN_SITE, C.siteUrl)],
  ];
  return { text, keyboard: kb(rows), linkPreview: coverPreview(ctx && ctx.assetOrigin) };
}

// The title and its note in brackets, the way the site's price table and
// request form write them.
function extraServiceBlock(svc) {
  return b(svc.title) + (svc.note ? '\n' + esc('(' + svc.note + ')') : '');
}

function screenServices() {
  const blocks = SERVICE_IDS.map((id) => b(C.services[id].title) + '\n' + esc(C.services[id].blurb))
    .concat(EXTRA_IDS.map((id) => extraServiceBlock(EXTRA_SERVICES[id])));
  const text = [b(C.servicesSection.heading), esc(C.servicesSection.lead)].concat(blocks).join('\n\n');
  const rows = SERVICE_IDS.map((id) => [btn(C.services[id].title, 's:' + id)])
    .concat(EXTRA_IDS.map((id) => [btn(EXTRA_SERVICES[id].title, 's:' + id)]));
  rows.push([btn(LBL_REQUEST, 'l'), btn(LBL_MENU_BACK, 'm')]);
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

// The site says nothing more about these services than the title, the note
// and the price, so the screen is exactly that plus the request button.
function screenExtraService(id) {
  if (!hasOwn(EXTRA_SERVICES, id)) return null;
  const svc = EXTRA_SERVICES[id];
  const text = [extraServiceBlock(svc), '', b(PRICE_HEADING), b(nbspPrice(svc.price))].join('\n');
  const rows = [[btn(LBL_REQUEST, 'l:' + id)], [btn(LBL_SERVICES_BACK, 's'), btn(LBL_MENU_BACK, 'm')]];
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

function screenService(id) {
  if (!hasOwn(C.services, id)) return null;
  const svc = C.services[id];
  // A page whose only price caption is "Стоимость" itself (razdel) shows just
  // the number under the heading, like the other pages show "caption — price".
  const prices = svc.prices.map((p) => (p.caption === PRICE_HEADING ? b(nbspPrice(p.price)) : priceLine(p.caption, p.price)));
  const text = [
    b(svc.title),
    i(svc.tagline),
    '',
    esc(svc.intro),
    '',
    b('Что входит в услугу'),
    bullets(svc.includes.map((c) => c.text)),
    '',
    b(PRICE_HEADING),
    prices.join('\n'),
  ].join('\n');
  const rows = [[btn(LBL_REQUEST, 'l:' + id)], [btn(LBL_HOW, 's:' + id + ':w')]];
  if (svc.faq.length) rows.push([btn(LBL_SERVICE_FAQ, 's:' + id + ':f')]);
  rows.push([urlBtn(LBL_SITE_PAGE, C.siteUrl + svc.slug)]);
  rows.push([btn(LBL_SERVICES_BACK, 's'), btn(LBL_MENU_BACK, 'm')]);
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

function screenServiceSteps(id) {
  if (!hasOwn(C.services, id)) return null;
  const svc = C.services[id];
  const text = [b(LBL_HOW), i(svc.title), '', svc.steps.map(numberedBlock).join('\n\n')].join('\n');
  const rows = [[btn(LBL_REQUEST, 'l:' + id)], [btn(LBL_SERVICE_BACK, 's:' + id), btn(LBL_MENU_BACK, 'm')]];
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

function screenServiceFaqList(id) {
  if (!hasOwn(C.services, id)) return null;
  const svc = C.services[id];
  if (!svc.faq.length) return null;
  const text = [b(LBL_SERVICE_FAQ), '', numberedList(svc.faq.map((q) => q.q))].join('\n');
  const rows = numberRows(svc.faq.length, (n) => 's:' + id + ':q' + n);
  rows.push([btn(LBL_SERVICE_BACK, 's:' + id), btn(LBL_MENU_BACK, 'm')]);
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

function screenServiceFaqAnswer(id, n) {
  if (!hasOwn(C.services, id)) return null;
  const svc = C.services[id];
  if (indexIn(svc.faq, n) < 0) return null;
  const text = qaBlock(svc.faq[n]);
  const rows = [[btn(LBL_REQUEST, 'l:' + id)], [btn(LBL_FAQ_BACK, 's:' + id + ':f'), btn(LBL_MENU_BACK, 'm')]];
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

function screenPrices() {
  const text = [
    b(C.priceSection.kicker),
    i(C.priceSection.heading),
    '',
    C.priceRows.map((r) => priceLine(r.label, r.price)).join('\n'),
    '',
    esc(C.priceSection.note),
  ].join('\n');
  const rows = [[btn(C.priceSection.ctaLabel, 'l')], [btn(LBL_MENU_BACK, 'm')]];
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

// "Как мы работаем" is two screens: the four steps, then (h:d) what the
// client gets in the end — one wall of text before.
function screenHow() {
  const text = [
    b(C.process.kicker),
    i(C.process.heading),
    '',
    C.process.steps.map(numberedBlock).join('\n\n'),
  ].join('\n');
  const rows = [[btn(C.cases.heading, 'h:d')], [btn(LBL_REQUEST, 'l'), btn(LBL_MENU_BACK, 'm')]];
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

function screenHowDocs() {
  const text = [
    b(C.cases.heading),
    esc(C.cases.lead),
    '',
    C.cases.docs.map(bulletTitleDescLine).join('\n'),
  ].join('\n');
  const rows = [[btn(LBL_REQUEST, 'l')], [btn('← ' + C.process.kicker, 'h'), btn(LBL_MENU_BACK, 'm')]];
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

function screenAbout() {
  const text = [
    b(C.about.kicker),
    b(C.about.heading),
    esc(C.about.paragraph1),
    esc(C.about.paragraph2),
    '',
    bullets(C.about.points.map((p) => p.text)),
  ].join('\n');
  const rows = [
    [btn(C.projects.heading, 'a:p')],
    [btn(C.awards.kicker, 'a:d')],
    [urlBtn(LBL_SRO, C.sroUrl)],
    [btn(LBL_REQUEST, 'l'), btn(LBL_MENU_BACK, 'm')],
  ];
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

function screenProjects() {
  const text = [
    b(C.projects.heading),
    esc(C.projects.lead),
    '',
    C.projects.items.map(titleDescBlock).join('\n\n'),
  ].join('\n');
  const rows = [[btn(LBL_REQUEST, 'l')], [btn(LBL_ABOUT_BACK, 'a'), btn(LBL_MENU_BACK, 'm')]];
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

// a:d is answered, not edited (sendMediaGroup first) — server.js special-
// cases route.type === 'documents'. These three pure helpers cover its parts.
function documentsMedia(origin) {
  return C.awards.items.map((a) => ({
    type: 'photo',
    media: assetBase(origin) + a.img,
    caption: b(a.title) + '\n' + esc(a.sub),
    parse_mode: 'HTML',
  }));
}
// Sent when sendMediaGroup fails: the same five documents as links.
function documentsFallback() {
  const lines = [b(C.awards.heading), esc(C.awards.lead), ''];
  for (const a of C.awards.items) lines.push('• <a href="' + esc(C.siteUrl + a.img) + '">' + esc(a.title + ' — ' + a.sub) + '</a>');
  const rows = [[btn(LBL_ABOUT_BACK, 'a'), btn(LBL_MENU_BACK, 'm')]];
  return { text: lines.join('\n'), keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}
// The message under the album. Telegram may hide per-photo captions in a
// collage, so the five documents are listed here too, in album order, with
// the caption's two lines joined by " — ".
function screenDocuments() {
  const list = C.awards.items.map((a, n) => (n + 1) + '. ' + esc(a.title) + ' — ' + esc(a.sub)).join('\n');
  const text = [b(C.awards.heading), esc(C.awards.lead), '', list].join('\n');
  const rows = [[btn(LBL_ABOUT_BACK, 'a'), btn(LBL_MENU_BACK, 'm')]];
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

function screenReviews() {
  const text = [
    b(C.reviews.heading),
    '',
    C.reviews.items
      .map((r) => '<blockquote>' + esc(r.text) + '</blockquote>\n' + esc(r.author) + ' · ' + esc(r.date))
      .join('\n\n'),
  ].join('\n');
  const rows = [[urlBtn(C.reviews.allLink + ' ↗', C.yandexReviewsUrl)], [btn(LBL_REQUEST, 'l'), btn(LBL_MENU_BACK, 'm')]];
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

function screenFaqList() {
  const text = [b(C.faqHeading), '', numberedList(C.faq.map((q) => q.q))].join('\n');
  const rows = numberRows(C.faq.length, (n) => 'q' + n);
  rows.push([btn(LBL_REQUEST, 'l'), btn(LBL_MENU_BACK, 'm')]);
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}
function screenFaqAnswer(n) {
  if (indexIn(C.faq, n) < 0) return null;
  const text = qaBlock(C.faq[n]);
  const rows = [[btn(LBL_REQUEST, 'l')], [btn(LBL_FAQ_BACK, 'f'), btn(LBL_MENU_BACK, 'm')]];
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

function screenContacts(contacts) {
  const c = contacts || {};
  const lines = [b('Контакты'), i(C.companyLine)];
  for (const ph of c.phones || []) {
    const num = esc(String(ph.display || '').replace(/^8\s/, '+7 '));
    const maxPart = ph.max ? ' · <a href="' + esc(ph.max) + '">MAX</a>' : '';
    lines.push('', esc(ph.region || ''));
    lines.push(num + maxPart);
  }
  lines.push('');
  if (c.email) lines.push('Почта: ' + esc(c.email));
  lines.push(esc(C.areaLine));
  lines.push(esc(C.hours));
  // From the site footer (bot-content.js), not from contacts.js: shown even
  // when contacts.js could not be loaded.
  if (C.legalLine) lines.push('', esc(C.legalLine));
  const text = lines.join('\n');

  const maxRow = (c.phones || [])
    .filter((ph) => ph.max)
    .map((ph) => urlBtn('MAX · ' + ph.short + ' ↗', ph.max));
  const rows = [];
  if (maxRow.length) rows.push(maxRow);
  rows.push([urlBtn(LBL_POLICY, C.policyUrl)]);
  rows.push([btn(LBL_REQUEST, 'l'), btn(LBL_MENU_BACK, 'm')]);
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

function screen(r, ctx) {
  if (!r) return null;
  switch (r.type) {
    case 'menu': return screenMenu(ctx);
    case 'services': return screenServices();
    case 'service': return screenService(r.id);
    case 'extraService': return screenExtraService(r.id);
    case 'serviceSteps': return screenServiceSteps(r.id);
    case 'serviceFaqList': return screenServiceFaqList(r.id);
    case 'serviceFaqAnswer': return screenServiceFaqAnswer(r.id, r.n);
    case 'prices': return screenPrices();
    case 'how': return screenHow();
    case 'howDocs': return screenHowDocs();
    case 'about': return screenAbout();
    case 'projects': return screenProjects();
    case 'documents': return screenDocuments();
    case 'reviews': return screenReviews();
    case 'faqList': return screenFaqList();
    case 'faqAnswer': return screenFaqAnswer(r.n);
    case 'contacts': return screenContacts(ctx && ctx.contacts);
    default: return null; // flow routes are not navigation screens
  }
}

// Plain block appended to undelivered-lead / failed-forward replies — not a
// full screen (no title, no buttons), so it stays separate from screenContacts.
function contactsBlock(contacts) {
  const c = contacts || {};
  const lines = [];
  for (const ph of c.phones || []) {
    const num = esc(String(ph.display || '').replace(/^8\s/, '+7 '));
    lines.push(esc(ph.region || '') + ': ' + num);
  }
  if (c.email) lines.push('Почта: ' + esc(c.email));
  return lines.join('\n');
}

// Telegram took neither copy of a lead or of a client's message: the client
// is sent to the engineer directly (the contacts block) and keeps the way to
// the menu (FIXES G6). HTML like every screen: the block is escaped.
const LEAD_UNDELIVERED_TEXT = 'Не получилось передать заявку инженеру — позвоните или напишите напрямую.';
const FORWARD_UNDELIVERED_TEXT = 'Не получилось передать сообщение инженеру — позвоните или напишите напрямую.';
function undeliveredScreen(headline, contacts) {
  const block = contactsBlock(contacts);
  const text = esc(headline) + (block ? '\n\n' + block : '');
  return { text, keyboard: kb([[btn(LBL_MENU_BACK, 'm')]]), linkPreview: DISABLE_PREVIEW };
}
function leadUndeliveredScreen(contacts) { return undeliveredScreen(LEAD_UNDELIVERED_TEXT, contacts); }
function forwardUndeliveredScreen(contacts) { return undeliveredScreen(FORWARD_UNDELIVERED_TEXT, contacts); }

// ---------------------------------------------------------------------------
// Lead flow (section 4-5, FIXES.md A3/A5/U1/U4/U13) — pure prompt/validation
// helpers. The step state machine and all I/O live in server.js.
// ---------------------------------------------------------------------------

const LBL_CANCEL = 'Отмена';
const LBL_SKIP = 'Пропустить';
const LBL_SEND = 'Согласен, отправить';
const LBL_EDIT = 'Изменить';

const CANCELLED_TEXT = 'Заявка отменена.';
const RESTART_TEXT = 'Начинаем заново.';
const STALE_TEXT = 'Заявка устарела — начните заново.';
const ALREADY_SENT_TEXT = 'Заявка уже отправлена.';
const NAME_INVALID_TEXT = 'Не получилось распознать имя. Напишите, как к вам обращаться.';
const PHONE_INVALID_TEXT = 'Не получилось распознать номер. Напишите его в формате +7 902 000-00-00 или нажмите «Отправить мой номер».';
const COMMENT_TOO_LONG_TEXT = 'Слишком длинно — уложитесь в 1000 символов.';
const BUSY_TEXT = 'Сейчас много обращений. Попробуйте позже или свяжитесь по контактам.';
const CHAT_CAP_TEXT = 'Слишком много заявок подряд. Попробуйте позже или свяжитесь по контактам.';
const FORWARD_ACK_TEXT = 'Сообщение передано. Кадастровый инженер свяжется с вами.\nЕсли не указали телефон — напишите его сюда же.';
// Already-escaped HTML line for the engineer's copy of a bot lead (after the
// "Telegram:" line): the only way to send one is the confirm screen's
// consent button.
const CONSENT_LEAD_LINE = 'Согласие на обработку персональных данных: дано в боте';

function leadServiceLabel(n) {
  return C.leadServices[n];
}

// Typed "Отмена" (any case, optional final dot) — the reply keyboard's own
// button sends exactly "Отмена".
function isCancelText(raw) {
  return typeof raw === 'string' && /^отмена\.?$/i.test(raw.trim());
}

function servicePickerPrompt() {
  const text = b('Заявка') + '\n' + esc('Выберите услугу.');
  const rows = LEAD_SERVICES.map((label, n) => [btn(label, 'l:o' + n)]);
  rows.push([btn(LBL_CANCEL, 'l:x')]);
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

// Zero-width, soft-hyphen, bidi and other invisible format characters are cut,
// and so are the blank "letters" that pass a letter check yet show nothing
// (FIXES G5): the Hangul fillers U+115F, U+1160, U+3164, U+FFA0, the braille
// blank U+2800, the Khmer inherent vowels U+17B4/U+17B5 and the Mongolian vowel
// separator U+180E. Control characters (newline, tab, ...) become a space.
const NAME_INVISIBLE_RE = /[\u00AD\u115F\u1160\u17B4\u17B5\u180E\u200B-\u200F\u202A-\u202E\u2060\u2066-\u2069\u2800\u3164\uFEFF\uFFA0]/g;
const NAME_CONTROL_RE = /\p{Cc}/gu;
function cleanName(raw) {
  return String(raw == null ? '' : raw)
    .replace(NAME_INVISIBLE_RE, '')
    .replace(NAME_CONTROL_RE, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

// Typed name: 1-80 characters after cleaning, at least one letter.
function validateName(raw) {
  const v = cleanName(raw);
  if (v.length < 1 || v.length > 80 || !/\p{L}/u.test(v)) return { ok: false };
  return { ok: true, value: v };
}

// Whole code points, at most `max` UTF-16 units: a cut through a surrogate
// pair is invalid text that Telegram rejects with the whole message.
function cutUnits(s, max) {
  let out = '';
  for (const ch of String(s)) {
    if (out.length + ch.length > max) break;
    out += ch;
  }
  return out;
}

// The client's Telegram first name for the "Меня зовут …" shortcut, cleaned
// like a typed name (no letter rule: it is their own profile name). '' when
// nothing visible is left — then the shortcut is not offered.
function telegramName(from) {
  const f = from && typeof from === 'object' ? from : {};
  return typeof f.first_name === 'string' ? cutUnits(cleanName(f.first_name), 80) : '';
}

// ctx = { from, service }; opts.retry re-asks after a name that did not pass.
function namePrompt(ctx, opts) {
  const c = ctx || {};
  let text;
  if (opts && opts.retry) text = esc(NAME_INVALID_TEXT);
  else text = (c.service ? esc('Услуга: ' + c.service) + '\n\n' : '') + esc('Как к вам обращаться?');
  const rows = [];
  const first = telegramName(c.from);
  if (first) rows.push([btn(Array.from('Меня зовут ' + first).slice(0, 40).join(''), 'l:me')]);
  rows.push([btn(LBL_CANCEL, 'l:x')]);
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

const PHONE_REPLY_KEYBOARD = {
  keyboard: [[{ text: 'Отправить мой номер', request_contact: true }], [{ text: LBL_CANCEL }]],
  resize_keyboard: true,
  one_time_keyboard: true,
  input_field_placeholder: '+7 ___ ___-__-__',
};

function phonePrompt() {
  const text = esc('Оставьте номер телефона — кадастровый инженер свяжется с вами.') +
    '\n\n' + esc('Нажмите «Отправить мой номер» или напишите номер сообщением.');
  return { text, replyKeyboard: PHONE_REPLY_KEYBOARD };
}

// 10-11 digits starting 7/8/9 -> "+7 XXX XXX-XX-XX"; otherwise the user's
// trimmed input as-is. The result still has to pass server.js's phoneOk()
// — the same check /api/lead applies — before the bot takes it.
function normalizePhone(raw) {
  const v = String(raw == null ? '' : raw).trim();
  const digits = v.replace(/\D/g, '');
  let ten = null;
  if (digits.length === 10 && /^[79]/.test(digits)) ten = digits;
  else if (digits.length === 11 && /^[78]/.test(digits)) ten = digits.slice(1);
  if (!ten) return v;
  return '+7 ' + ten.slice(0, 3) + ' ' + ten.slice(3, 6) + '-' + ten.slice(6, 8) + '-' + ten.slice(8, 10);
}

// A shared contact's number. Telegram sends international numbers without
// "+": Russian ones are formatted like a typed number, any other one that
// starts with a digit gets its "+".
function contactPhone(raw) {
  const v = String(raw == null ? '' : raw).trim();
  const n = normalizePhone(v);
  if (n !== v) return n;
  return /^\d/.test(v) ? '+' + v : v;
}

// Sent without parse_mode, so nothing is escaped (an accepted phone holds
// only digits, spaces and "+()-" anyway).
function phoneSetText(phone) {
  return 'Телефон: ' + phone;
}

// opts.tooLong re-asks after a comment over the limit, same buttons.
function commentPrompt(opts) {
  const text = (opts && opts.tooLong) ? esc(COMMENT_TOO_LONG_TEXT) : esc('Кратко опишите ситуацию (необязательно).');
  const rows = [[btn(LBL_SKIP, 'l:skip'), btn(LBL_CANCEL, 'l:x')]];
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}
function validateComment(raw) {
  const v = String(raw == null ? '' : raw).trim();
  if (v.length > 1000) return { ok: false };
  return { ok: true, value: v };
}

function summaryLines(state) {
  const s = state || {};
  const lines = [];
  if (s.name) lines.push('Имя: ' + esc(s.name));
  if (s.phone) lines.push('Телефон: ' + esc(s.phone));
  if (s.service) lines.push('Услуга: ' + esc(s.service));
  if (s.comment) lines.push('Комментарий: ' + esc(s.comment));
  return lines;
}

// The site form's consent checkbox label word for word (LeadModal.dc.html,
// read by the generator), its policy link made absolute.
const CONSENT_LINE = esc(C.consent.text) + ' <a href="' + esc(C.policyUrl) + '">' + esc(C.consent.link) + '</a>' + esc(C.consent.tail);

function confirmPrompt(state) {
  const text = [b('Проверьте заявку')].concat(summaryLines(state), ['', CONSENT_LINE]).join('\n');
  const rows = [[btn(LBL_SEND, 'l:ok')], [btn(LBL_EDIT, 'l:e'), btn(LBL_CANCEL, 'l:x')]];
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

// "Изменить" edits one field and comes back to the confirm screen.
function editMenuPrompt() {
  const text = b('Что изменить?');
  const rows = [
    [btn('Услуга', 'l:e:s'), btn('Имя', 'l:e:n')],
    [btn('Телефон', 'l:e:p'), btn('Комментарий', 'l:e:c')],
    [btn('← К заявке', 'l:b')],
  ];
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

// "Заявка отправлена. Кадастровый инженер свяжется с вами." from LeadModal,
// split at its one ". " into the bold headline and the plain line under it.
const SENT_PARTS = C.leadSentHeadline.split('. ');
const SENT_TITLE = SENT_PARTS[0];
const SENT_BODY = SENT_PARTS.slice(1).join('. ');

function sentText(state) {
  const text = [b(SENT_TITLE), esc(SENT_BODY), '']
    .concat(summaryLines(state), ['', esc('Если нужно, опишите задачу подробнее — напишите сюда же.')])
    .join('\n');
  const rows = [[btn(LBL_MENU_BACK, 'm')]];
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

// No exact copy is given for this one in SPEC.md (section 4: "the sent text
// says it was not sent to the engineer") — authored to state that fact
// plainly, same tone as the rest of the bot.
function ownerSentText(state) {
  const text = [b('Тестовая заявка отправлена'), esc('Это тестовый прогон — инженеру она не уйдёт.'), '']
    .concat(summaryLines(state))
    .join('\n');
  const rows = [[btn(LBL_MENU_BACK, 'm')]];
  return { text, keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

// The shared hourly cap refused the lead (it is kept in the log): the client
// gets another way to reach the engineer, and the confirm screen stays.
function busyScreen() {
  const rows = [[btn('Контакты', 'c')], [btn(LBL_MENU_BACK, 'm')]];
  return { text: esc(BUSY_TEXT), keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

// The chat's own cap (5 leads in 10 minutes) refused the lead (FIXES G8):
// "wait a minute" would be wrong, so the busy reply's way out instead; the
// confirm screen stays, as with the busy reply.
function chatCapScreen() {
  const rows = [[btn('Контакты', 'c')], [btn(LBL_MENU_BACK, 'm')]];
  return { text: esc(CHAT_CAP_TEXT), keyboard: kb(rows), linkPreview: DISABLE_PREVIEW };
}

// Reply to a message forwarded to the engineer. A shared contact usually
// comes from the phone step's reply keyboard (a flow that expired or was
// lost on restart), so that reply takes the keyboard down instead of
// carrying buttons — a message cannot do both.
function forwardAck(isContact) {
  return {
    text: FORWARD_ACK_TEXT,
    replyMarkup: isContact ? { remove_keyboard: true } : kb([[btn(LBL_REQUEST, 'l'), btn(LBL_MENU_BACK, 'm')]]),
  };
}

function buildLeadPayload(state) {
  const s = state || {};
  return {
    name: s.name || '',
    phone: s.phone || '',
    service: s.service || '',
    message: s.comment || '',
    page: 'Telegram-бот',
  };
}

// A Telegram user id fit for a tg://user link (a positive integer, as
// Telegram sends it), or '' — then no link is built rather than a dead one.
function telegramUserId(f) {
  const id = f.id;
  if (typeof id === 'number' && Number.isSafeInteger(id) && id > 0) return String(id);
  if (typeof id === 'string' && /^[1-9][0-9]{0,15}$/.test(id)) return id;
  return '';
}

// Already-escaped HTML line identifying the Telegram sender: in buildLeadMessage's
// opts.extra (server.js, section 6) and in the header of every message forwarded
// to the lead chats (FIXES G3), so a client without a username or a phone can
// still be reached.
function telegramUserLine(from) {
  const f = from && typeof from === 'object' ? from : {};
  const label = esc(f.username ? '@' + f.username : ([f.first_name, f.last_name].filter(Boolean).join(' ') || 'пользователь'));
  const id = telegramUserId(f);
  return 'Telegram: ' + (id ? '<a href="tg://user?id=' + id + '">' + label + '</a>' : label);
}

const leadFlow = {
  LEAD_SERVICES,
  SERVICE_ID_TO_LM_INDEX,
  leadServiceLabel,
  isCancelText,
  servicePickerPrompt,
  cleanName,
  validateName,
  telegramName,
  namePrompt,
  NAME_INVALID_TEXT,
  PHONE_REPLY_KEYBOARD,
  phonePrompt,
  PHONE_INVALID_TEXT,
  normalizePhone,
  contactPhone,
  phoneSetText,
  commentPrompt,
  COMMENT_TOO_LONG_TEXT,
  validateComment,
  summaryLines,
  confirmPrompt,
  editMenuPrompt,
  sentText,
  ownerSentText,
  busyScreen,
  BUSY_TEXT,
  chatCapScreen,
  CHAT_CAP_TEXT,
  forwardAck,
  FORWARD_ACK_TEXT,
  CANCELLED_TEXT,
  RESTART_TEXT,
  STALE_TEXT,
  ALREADY_SENT_TEXT,
  CONSENT_LEAD_LINE,
  buildLeadPayload,
  telegramUserLine,
};

module.exports = {
  escapeHtml,
  nbspPrice,
  route,
  commandRoute,
  startPayloadRoute,
  isFlowRoute,
  screen,
  assetBase,
  documentsMedia,
  documentsFallback,
  contactsBlock,
  LEAD_UNDELIVERED_TEXT,
  FORWARD_UNDELIVERED_TEXT,
  leadUndeliveredScreen,
  forwardUndeliveredScreen,
  leadFlow,
};
